### PR TITLE
141- added information on integration testing (good practices)

### LINKED ISSUE #141: Add information on integration testing
Testing page currently lacks detail on integration and end to end testing. Page should cover what the purpose of these tests is, when to write them and what to think about when writing them. Users have expressed an interest in seeing an example of good practice

### PR DESCRIPTION
**Pull request by giuliag92**

### CODE REVIEW

**Comment by giuliag92** [comment]
@sarahcollyer @CHCRowley to review before merging :)

**Review by sarahcollyer — APPROVED** [review]
Looks good to me!

**Review by CHCRowley — COMMENTED** [review]
Looks good :)

**Comment by ellie-o** [comment]
This section is fine, but a new ticket to be created to add general intro to integration ticket to pull the sections in this chapter together

**Pull request merged**
