### PR TITLE
Hannah is doing a proofread

### PR DESCRIPTION
**Pull request by alexander-newton**

### CODE REVIEW

**Comment by foster999** [comment]
Thanks for these @statshan!

I've removed the copyrighted cartoon in the latest change, but it's not live yet.

The code blocks are actually just formatted text. The formatting mimics how this would appear in a typical code editor, so I think this is probably OK. You can select the text and could likely screen read it - though it would sound like some one reading through code...

I agree about the image that could be a table - will look to replace or remove that. 

Please feel free to make any suggestions that are general to the whole book in the comments here. We can do some kind of find and replace to fix them throughout then, to save you editing each instance 😊

**Comment by statshan** [comment]
Heya, ta for that.

It was the other cartoon – not the Dilbert one, right?
Alex called it something but I don’t know what he said – the stickman one?
If you can find out about copyright I guess from a legal perspective it would be OK to leave it in.
Or better yet – make your own version – this would also then make it eaiser to make an accessible version!
The regs say you can’t have images of text, but I do like the cartoon, if you could make an accessible version of it – like a text document download with the text of the cartoon in? A bit like a script? That would be fine. Or you can link to the image of the cartoon (we’re not responsible for the accessibility of the content of external sites – although we should always try to link to accessible content when possible).

I don’t mind going through and editing if you don’t mind me doing it!

Ta,

Han

**Comment by statshan** [comment]
Oh also – I will try to test the code blocks with my screenreader software and let you know

**Comment by alexander-newton** [comment]
https://www.explainxkcd.com/wiki/index.php/Main_Page has transcripts

**Comment by statshan** [comment]
AH yeah this is good

**Comment by foster999** [comment]
Looks like the stickman cartoons are [fine for non-commercial use, if we continue to link back to the original content](https://xkcd.com/license.html) 😄

The images are hotlinked directly from the original source, so aren't technically coming from our site. But I agree it would be best to provide transcripts. Would it be best to include these as `alt-text`, or would a [link to the transcript header on that other site](https://www.explainxkcd.com/wiki/index.php/1261:_Shake_That#Transcript) be better?

Really keen to hear how the screen reader handles the code blocks and also the coloured boxes that we use to highlight important stuff throughout. We've had suggestions to use more of these to highlight good vs bad examples, so keen to know if we need to tweak these to make them accessible.

**Review by shilohd — APPROVED** [review]
All changes are in line with writing about statistics style guidance/WCAG accessibility guidelines.

**Pull request merged**
