### PR TITLE
125 add a ci or pre commit workflow to lint or format markdown

### LINKED ISSUE #125: Add a CI or pre-commit workflow to lint or format markdown
The book uses the MyST flavour of Markdown. We want to automatically lint or format this, to ensure that style is consistent throughout

### PR DESCRIPTION
**Pull request by RuSnook**
I've added a pre-commit linter, with some adjustments to the default config. Not sure if I've set up the requirements correctly, but also not sure how to check this, so good to see if this works for reviewers.

### CODE REVIEW

**Comment by RuSnook** [comment]
This is failing to build due to the new link checker that's been added. To fix this I would need to push much larger changes which would distract from the goal of this PR. 

I suggest that the link gets updated first and that gets pulled into this branch. I think that would allow me to do the updates need for this linter to pass as a separate PR.

**Comment by foster999** [comment]
Thanks @RuSnook, I think adding the changes to satisfy the linter would come under the same end goal for the PR. The goal could be rephrased as "Add linter to standardise Markdown style"?

**Comment by foster999** [comment]
Got this working pretty quickly by running `pip install -r dev-dependencies.txt` and then `pre-commit install`. It runs on the document that is edited in the current commit, and when running `pre-commit run --all` it shows issues across files. So looks like it's working as expected locally :)

**Comment by RuSnook** [comment]
> pre-commit install

have updated the readme to include this guidance.

Once the other PRs are merged I'll do a final  update to the linked branch with updates for the book to make it conform to this hook.

DO NOT MERGE UNTIL THIS IS DONE.

**Review by shilohd — APPROVED** [review]

**Pull request merged**
