### PR TITLE
Added testing SQL section

### LINKED ISSUE #111: Add subsection on testing SQL
[For example](https://stackoverflow.com/questions/754527/best-way-to-test-sql-queries/754570#754570)

### PR DESCRIPTION
**Pull request by giro090**

### CODE REVIEW

**Review by sarahcollyer — CHANGES_REQUESTED** [review]
Looks good! Small tweak to grammar in the second sentence:

> In SQL, single queries are often contain many different parts.

Can you remove the "are" please, then happy to approve and merge.

**Comment by giro090** [comment]
Thanks for spotting this! Will fix.

**Review by sarahcollyer — DISMISSED** [review]
Looks good!

**Review by zarbspace — APPROVED** [review]
Approved

**Pull request merged**
