### PR TITLE
Reviewed, added and rejigged code_documentation content

### PR DESCRIPTION
**Pull request by finnkauski**
This PR updates the content mainly in the code documentation chapter of your book from the work that Campus are doing to make sure we contribute our views to this awesome document. Happy to answer any questions either through comments here (also happy to make sensible changes) but if not, contact me through work Skype - Arthur Eidukas

### CODE REVIEW

**Comment by finnkauski** [comment]
I've spotted a few spelling mistakes and just grammar inconsistencies as well. Once you've provided comments on the fundamental changes you'd like to see I'll go through again and try to make sure the grammar is fine alongside the changes you suggest. Please don't get bogged down in that level of detail while the value is the review of the content and the form its delivered.

**Review by foster999 — COMMENTED** [review]
Thanks for the review and contributions, it's really great to have another pairs of eyes on the guidance!

The changes here look great. I noted a few spelling/grammar mistakes etc, but wouldn't have any comments on changing the message. We might need to break some of the longer sentences down into shorter text, but the prose reads better than the many one-liners that I'd written before.

More general thoughts:
* This section doesn't benefit from the star ratings, so happy to drop them.
* Refactoring paragraphs onto single lines has made the final diffs here more difficult to interpret, so if this strongly preferred I'll refactor the rest of the book in line with this (I have no preference).
* For accessibility, it's important that hyperlink text is descriptive. E.g. something like `[here](link)` would be hard to interpret by screen reader. It's often tricky to implement this well, but I'll add something to the contribution guide on this.

@alexander-newton mentioned your suggestion of a box at the start of each section that outlines "good practice in this area looks like:". This is a really great idea - it'll help analysts to focus their effort where it's most needed. We should add this to intros across the book.

Similarly, we've had requests for a separate page that highlights these key good practices across all sections of the book. This would link back to each relevant section, but give analysts an overview of what is expected. Our idea for an "analysis maturity model" would look to address this in the long term.

**Comment by foster999** [comment]
I considered adding something around type hinting, but I'm not sure if there's a decent implementation in R. This might belong in coding practices instead, but I prefer this over listing type in the docstrings - mostly cause it allows static type checking (e.g. `mypy` and friends)

**Comment by foster999** [comment]
I wonder if script-level docstrings should go in a separate paragraph? It's good to include these, especially for script-based analysis. We might provide or point to a simple example of this in practice.

**Comment by finnkauski** [comment]
I think If You're broadly happy with the structure, and obviously with the spelling mistakes / hyperlinks fixed, we could maybe merge this in and start building on top of it. I will address the issues in a bit and hopefully we can have this merged in today. 

With respects to Stars, we sort of said that they are more misleading than useful. If someone visits a page of this guidance that has stars without knowing the context for them, you can't tell what they are stars off - difficulty? importance? So we decided that we will hopefully provide pretty sterile guidance, and the maturity stuff you're working on will probably address what the stars are trying to do now. 

I have done quite a bit of work on the core programming practices so far, but progress is slow at the moment. I will make a draft PR on that as well in a bit, it would be great if you provided comments as I keep adding to it.

**Comment by finnkauski** [comment]
Fixed spelling where I could find issues. Make sure it is all fixed with respect to the spelling issues you found before and we should merge this in if you are happy. My focus now is the core programming practices chapters so would be nice to not think about this. 

Type hinting probably needs to go into core-programming, but I'd say even though you can mention it, in practice its a bit of a pain to do as the analysts will have to find type information for third party packages otherwise type checkers won't be as useful as they can be. Which is a lot to ask from an analyst. I'd say add them in the linting section of `core_programming` as a side note. I can do that as I'm rejigging that chapter anyway, just send me over some preprepped material on what you wanna say on type checkers and I'll have a look and incorporate it in the core_programming PR. 

Perhaps the real value here is to tie in things like https://pre-commit.com to check if you have docstrings on all your functions or for example tie this in with testing chapters to cover docstring coverage checks alongside test coverage checks during testing. 

You can make the tweaks to include script level docstrings as well. But perhaps do it after this is merged in?

**Comment by foster999** [comment]
I'll run through this again this afternoon and then get it merged 👍 

Agree that adding other bits here can go on the todo pile - best to prioritise getting the existing content up to scratch.

**Review by foster999 — APPROVED** [review]

**Pull request merged**
